"""
ris_exporter.py — Exportador de referências acadêmicas no formato RIS.

Suporta:
  - Artigos acadêmicos (arXiv, PubMed, Semantic Scholar)
  - Sites técnicos
  - Repositórios de código (GitHub)

Formato compatível com Zotero, Mendeley, EndNote.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from datetime import datetime
from typing import Any, List

logger = logging.getLogger("ris_exporter")


@dataclass
class RISEntry:
    """Uma entrada RIS para exportação."""

    ref_type: str  # JOUR, BOOK, CHAP, ELEC, COMP, etc.
    fields: dict[str, str]  # TI, AU, PY, UR, AB, etc.

    def to_ris(self) -> str:
        """Converte a entrada para formato RIS."""
        lines = [f"TY  - {self.ref_type}"]
        for key, value in self.fields.items():
            if value:
                # RIS usa múltiplas linhas para campos com o mesmo código
                if isinstance(value, list):
                    for v in value:
                        lines.append(f"{key}  - {v}")
                else:
                    lines.append(f"{key}  - {value}")
        lines.append("ER  -")
        return "\n".join(lines)


class RISExporter:
    """Exportador de referências para formato RIS."""

    @staticmethod
    def from_search_result(result: dict[str, Any], index: int = 0) -> RISEntry | None:
        """
        Cria uma entrada RIS a partir de um SearchResult.

        Args:
            result: Dicionário com campos title, authors, year, url, etc.
            index: Índice para gerar identificador único se necessário.

        Returns:
            RISEntry ou None se dados insuficientes.
        """
        title = result.get("title", "")
        authors = result.get("authors", [])
        url = result.get("url", "")
        year = result.get("year", datetime.now().year)
        abstract = result.get("abstract", "")
        source = result.get("source", "web")

        if not title:
            return None

        # Normaliza autor(es)
        author_str = RISExporter._format_authors(authors)

        # Determina o tipo de referência RIS
        ris_type = RISExporter._determine_ris_type(source, result)

        # Campos comuns
        fields: dict[str, str] = {
            "TI": title,  # Title
            "PY": str(year),  # Year
            "UR": url,  # URL
        }

        if authors:
            fields["AU"] = author_str  # Author

        if abstract:
            fields["AB"] = abstract  # Abstract

        # Campos específicos por tipo
        if ris_type == "JOUR":  # Journal Article
            if journal := result.get("journal"):
                fields["JO"] = journal  # Journal
            if volume := result.get("volume"):
                fields["VL"] = volume  # Volume
            if pages := result.get("pages"):
                parts = str(pages).split("-")
                if len(parts) == 2:
                    fields["SP"] = parts[0]  # Start Page
                    fields["EP"] = parts[1]  # End Page
                else:
                    fields["SP"] = parts[0] if parts else ""  # Single page or just first part

        fields["DA"] = datetime.now().strftime("%Y/%m/%d")  # Date Created

        return RISEntry(ref_type=ris_type, fields=fields)

    @staticmethod
    def export_batch(
        results: list[dict[str, Any]], filename: str | None = None
    ) -> str:
        """
        Exporta múltiplas referências para um único arquivo .ris.

        Args:
            results: Lista de dicionários de resultados de pesquisa.
            filename: Nome do arquivo opcional (se None, retorna string).

        Returns:
            Conteúdo completo do arquivo .ris.
        """
        entries: list[str] = [
            "Generated by Smart Research Agent",
            f"Date: {datetime.now().isoformat()}",
            "",
        ]

        for idx, result in enumerate(results):
            entry = RISExporter.from_search_result(result, idx)
            if entry:
                entries.append(entry.to_ris())
                entries.append("")  # Linha em branco entre entradas

        content = "\n".join(entries).strip() + "\n"

        if filename:
            Path(filename).write_text(content, encoding="utf-8")
            logger.info("RISExporter: exportado %d entradas para %s", len(entries), filename)

        return content

    # ── Helpers internos ──────────────────────────────────────────────────────

    @staticmethod
    def _format_authors(authors: list[str] | str) -> List[str]:
        """Formata lista de autores para formato RIS (um por linha)."""
        if isinstance(authors, str):
            try:
                # Tenta converter string JSON para lista
                import json

                if isinstance(authors, str):
                    try:
                        parsed = json.loads(authors)
                        if isinstance(parsed, list):
                            return [str(a) for a in parsed]
                    except json.JSONDecodeError:
                        pass
            except ImportError:
                pass
            # Se não for JSON, trata como uma string simples
            authors = [authors] if authors else []

        if not authors:
            return ["Anonymous"]

        formatted = []
        for author in authors[:20]:  # Limite razoável para evitar output excessivo
            author_str = str(author).strip()
            if not author_str:
                continue

            # Tenta formatar como "Sobrenome, Nome" se houver espaço
            parts = re.split(r"\s+", author_str)
            if len(parts) >= 2:
                # Assume que a última parte é o sobrenome
                formatted.append(f"{parts[-1]}, {' '.join(parts[:-1])}")
            else:
                # Se só tiver uma palavra, use como está
                formatted.append(author_str)

        return filtered if (filtered := [f for f in formatted if f]) else ["Autor Desconhecido"]

    @staticmethod
    def _determine_ris_type(source: str, result: dict[str, Any]) -> str:
        """Determina o tipo RIS apropriado baseado na fonte e conteúdo."""
        source_lower = str(source).lower()
        title_lower = str(result.get("title", "")).lower()

        # Verifica indicadores específicos
        if any(term in source_lower for term in ["arxiv", "pubmed", "medline"]):
            return "JOUR"  # Journal Article
        if any(term in source_lower for term in ["github", "gitlab", "bitbucket"]):
            return "ELEC"  # Electronic Source
        if "conference" in title_lower or "proceeding" in title_lower:
            return "CONF"  # Conference Paper
        if any(term in source_lower for term in ["journal", "review"]):
            return "JOUR"
        if any(term in source_lower for term in ["book", "ebook"]):
            return "BOOK"
        if "thesis" in title_lower or "dissertation" in title_lower:
            return "THES"  # Thesis

        # Tipo padrão para fontes web/desconhecidas
        return "ELEC"  # Electronic Source (mais seguro que GEN para web)


# Import necessário para Path
from pathlib import Path